import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'

const eslintConfig = defineConfig([
  // Spread the official Next.js flat config (includes TS, React, core-web-vitals)
  ...nextVitals,

  // Ignore build output and generated files
  globalIgnores([
    '.next/**',
    'node_modules/**',
    'sanity/types.ts', // auto-generated by sanity typegen
  ]),

  // Project-specific overrides
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'react/no-unescaped-entities': 'off',
      '@next/next/no-img-element': 'warn',
    },
  },
])

export default eslintConfig